version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=shop_name_plate
      - MARIADB_USER=shop_name_plate
      - MARIADB_PASSWORD=shop_name_plate
      - MARIADB_DATABASE=shop_name_plate
      - MARIADB_PASSWORD_HASH=shop_name_plate
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    build: opencart-4.0.1.1/.
    ports:
      - "8080:80"
    volumes:
      - '/Users/apple/projects/shop-name-plate/app/opencart_data:/var/www/html/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local