version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=shop_name_plate
      - MARIADB_USER=shop_name_plate
      - MARIADB_PASSWORD=shop_name_plate
      - MARIADB_DATABASE=shop_name_plate
      - MARIADB_PASSWORD_HASH=shop_name_plate
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    build: opencart-4.0.1.1/.
    ports:
      - "8080:80"
    volumes:
      - '/Users/apple/projects/shop-name-plate/app/opencart_data:/var/www/html/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  # opencart_data:
  #   driver: local
  # opencart_storage_data:
  #   driver: local







# version: '3.8'

# volumes:
#   datafiles:

# services:

#   mysql:
#     image: mysql:8.0.0
#     container_name: mysql6
#     environment:
#       - MYSQL_ROOT_PASSWORD=sopno_1818120**
#       - MYSQL_TCP_PORT=3306
#       - TZ=Asia/Dhaka
#     volumes:
#       - datafiles:/var/lib/mysql
#     restart: always

#   website:
#     container_name: php6
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - DB_HOST=mysql
#       - MYSQL_DBPORT=3306
#       - DB_USERNAME=sopnobari_tuneb
#       - DB_PASSWORD=sopno_1818120**
#       - DB_NAME=sopnobari_sopno
#     ports:
#       - "3050:80"
#       - "3051:443"
#     depends_on:
#       - mysql